sonar.projectKey=gpullano_GalaxyTruckerGruppo5
sonar.organization=progetto-java-galaxy-trucker-gruppo5

#--------------------------------------------------------------------------------
# DATI OPZIONALI (ma utili)
#--------------------------------------------------------------------------------
# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=GalaxyTruckerGruppo5
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# Assicurati che questa riga sia decommentata e corretta:
sonar.sources=src

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# ---------> AGGIUNGI O MODIFICA QUESTA RIGA <---------
# Path to the compiled bytecode (relative to sonar-project.properties)
# Se i tuoi file .class sono nella cartella 'bin' alla radice del progetto:
sonar.java.binaries=bin
